# Generated by Django 4.2.10 on 2025-03-29 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip_planner', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eldlog',
            options={'ordering': ['date']},
        ),
        migrations.AlterModelOptions(
            name='routesegment',
            options={'ordering': ['start_time']},
        ),
        migrations.AddField(
            model_name='routesegment',
            name='end_coordinates',
            field=models.JSONField(blank=True, help_text='[longitude, latitude]', null=True),
        ),
        migrations.AddField(
            model_name='routesegment',
            name='start_coordinates',
            field=models.JSONField(blank=True, help_text='[longitude, latitude]', null=True),
        ),
        migrations.AlterField(
            model_name='routesegment',
            name='segment_type',
            field=models.CharField(choices=[('DRIVE', 'Driving'), ('REST', 'Rest Period'), ('FUEL', 'Fueling Stop'), ('PICKUP', 'Pickup'), ('DROPOFF', 'Dropoff'), ('START', 'Trip Start')], max_length=50),
        ),
    ]
