# Generated by Django 4.2.10 on 2025-03-29 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip_planner', '0002_alter_eldlog_options_alter_routesegment_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='routesegment',
            name='segment_type',
            field=models.CharField(choices=[('DRIVE', 'Driving'), ('REST', 'Rest Period'), ('FUEL', 'Fueling Stop'), ('PICKUP', 'Pickup'), ('DROPOFF', 'Dropoff'), ('START', 'Trip Start'), ('WAYPOINT', 'Waypoint')], max_length=50),
        ),
    ]
