apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: eld-trip-planner
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/bruceminanga/Eld-trip-planner.git # Your repo
    targetRevision: HEAD
    path: kubernetes/base # We'll start by deploying the base
  destination:
    server: https://kubernetes.default.svc
    namespace: eld-trip-planner
  syncPolicy:
    automated: { prune: true, selfHeal: true }
    syncOptions: [CreateNamespace=true]
