# FILE: kubernetes/base/backend-deployment.yml (Corrected)
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: eld-trip-planner
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: bruceminanga/eld-trip-planner-backend
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
          # THIS IS THE SINGLE, CORRECT envFrom BLOCK
          envFrom:
            - configMapRef:
                name: backend-config
            - secretRef:
                name: backend-secret
          resources:
            requests:
              memory: "256Mi"
              cpu: "100m" # 1/10th of a CPU core
            limits:
              memory: "512Mi"
              cpu: "500m" # Half of a CPU core
