apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: backend-secret-pointer
  namespace: eld-trip-planner
spec:
  # Reference the SecretStore that knows how to talk to Vault
  secretStoreRef:
    name: vault-backend
    kind: SecretStore

  # Define the Kubernetes Secret that ESO should create
  target:
    name: backend-secret # This must match the name in your deployment's envFrom
    creationPolicy: Owner

  # Define which secrets to fetch from the external store
  data:
    - secretKey: GEOAPIFY_API_KEY
      remoteRef:
        key: secret/eld-trip-planner # The path in Vault
        property: GEOAPIFY_API_KEY # The key within that path

    - secretKey: SECRET_KEY
      remoteRef:
        key: secret/eld-trip-planner
        property: SECRET_KEY
