# FILE: kubernetes/overlays/development/kustomization.yml (CORRECTED)
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
  - ../../base

resources:
  - configmap.yml
  - ingress.yml
  - secret-store.yml
  - external-secret.yml

images:
  - name: bruceminanga/eld-trip-planner-backend
    newTag: latest
  - name: bruceminanga/eld-trip-planner-frontend
    newTag: latest
