apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: vault-backend
  namespace: eld-trip-planner
spec:
  provider:
    vault:
      # The address of our Vault service
      server: "http://vault.eld-trip-planner.svc.cluster.local:8200"
      path: "secret"
      version: "v2"
      auth:
        # Use the token from the secret we just created
        tokenSecretRef:
          name: "vault-token"
          key: "token"
